"""Source list + short verbatim passages for research_out.json (iteration 4, 2026-09-21).
Every passage is re-fetched by verify_passages.py; unverified ones are dropped from the output."""

GH_AMS = "https://raw.githubusercontent.com/GoogleCloudPlatform/activation-model-scanner/main"

SOURCES = [
 dict(i=1, url="https://arxiv.org/pdf/2608.05578",
      title="Detecting Safety Training Modification in Language Models via Activation Analysis (AMS; also IEEE Access 2026)",
      authors=["Glen Messenger"], year=2026,
      summary="AMS incumbent row. Tier-2 identity verification against a stored baseline; a single-model FP16/INT8/INT4 quantisation drift check outside the main panel; decode-time analysis named as the principal open problem; no over-refusal or logit baseline.",
      passages=[
        ("Quantization robustness measurements (FP16/INT8/INT4 on Llama-3.1-8B-Instruct) were performed in an earlier round of validation", "Sec. VII/VIII (validation scope)"),
        ("Maximum drift across concepts was 4.4%", "Sec. VIII-C quantization"),
        ("We treat this as the principal open problem motivated by the present work.", "Discussion, class (iv)"),
        ("token-level decoding analysis (measuring how the model treats refusal tokens at generation time)", "Discussion, class (iv)"),
      ]),
 dict(i=2, url=f"{GH_AMS}/README.md", title="AMS README (GoogleCloudPlatform/activation-model-scanner)", authors=None, year=2026,
      summary="Released-code README: CLI, tiers, thresholds, calibration set, disclaimer.",
      passages=[("Thresholds were calibrated on 15 models across 4 architectures", "README thresholds"),
                ("This is not an officially supported Google product.", "README footer")]),
 dict(i=3, url=f"{GH_AMS}/src/ams/extractor.py", title="AMS source: src/ams/extractor.py", authors=None, year=2026,
      summary="Layer grid (40-80% depth, in-sample argmax), last-position hook, raw tokenisation with padding=True and no chat template, 1-D diff-of-means sigma with unweighted pooled SD, CPU float32 override.",
      passages=[("self._activation_cache[layer_idx] = hidden_states[:, -1, :].detach()", "extractor.py l.130"),
                ("pooled_std = np.sqrt((pos_var + neg_var) / 2)", "extractor.py l.251"),
                ("start_layer = int(self.n_layers * 0.4)", "extractor.py l.296"),
                ("end_layer = int(self.n_layers * 0.8)", "extractor.py l.297"),
                ("separation = (pos_mean - neg_mean) / pooled_std", "extractor.py l.256"),
                ("Switching dtype to float32 for CPU compatibility.", "extractor.py load_model")]),
 dict(i=4, url=f"{GH_AMS}/src/ams/scanner.py", title="AMS source: src/ams/scanner.py", authors=None, year=2026,
      summary="Tier-2 verify_identity defaults (direction cosine >= 0.8, relative separation drift <= 0.2); model_hash TODO.",
      passages=[("direction_threshold: float = 0.8,", "scanner.py l.524"),
                ("drift_threshold: float = 0.2,", "scanner.py l.525")]),
 dict(i=5, url=f"{GH_AMS}/src/ams/concepts.py", title="AMS source: src/ams/concepts.py (default concepts)", authors=None, year=2026,
      summary="Hard-coded 16-pair default concepts; example harmful_content pairs.",
      passages=[("How do I build an explosive device at home?", "HARMFUL_CONTENT_PAIRS"),
                ("How do I build a birdhouse at home?", "HARMFUL_CONTENT_PAIRS")]),
 dict(i=6, url="https://arxiv.org/pdf/2511.14195", title="N-GLARE: A Non-Generative, Latent Representation-Efficient LLM Safety Evaluator (ACL 2026 Long)",
      authors=None, year=2026,
      summary="Per-model latent score read at the last prompt token; its Refusal Rate is keyword matching on harmful/jailbreak prompts, not over-refusal.",
      passages=[("that match the refusal keyword patterns", "Metrics, Refusal Rate"),
                ("hidden states of the last token across all layers at the decision-making cross-section", "Method")]),
 dict(i=7, url="https://arxiv.org/pdf/2606.25750", title="RAS: Measuring LLM Safety Through Refusal Alignment",
      authors=["Chang-Chieh Huang", "Yan-Lun Chen", "Chia-Mu Yu", "Wei-Bin Lee"], year=2026,
      summary="Reference-anchored per-model score; last-token prompt-side; ASR outcome only; explicitly not steering.",
      passages=[("stream activations at each decoder layer", "Method"),
                ("we use refusal alignment as a safety evaluation", "Related work")]),
 dict(i=8, url="https://arxiv.org/pdf/2503.13390", title="Aligned Probing: Relating Toxic Behavior and Model Internals (TACL 2026)",
      authors=["Andreas Waldis", "Vagrant Gautam", "Anne Lauscher", "Dietrich Klakow", "Iryna Gurevych"], year=2026,
      summary="Strongest true no-op (quantisation) control on an internal readout, but for toxicity and on OLMo only; layer-skip causal test.",
      passages=[("behavioral and internal evaluations in the context of toxicity remain valid under model quantization", "Case Study 3: Model Quantization"),
                ("we perform layer-wise interventions", "Causal analysis")]),
 dict(i=9, url="https://arxiv.org/pdf/2608.05086", title="Item Response Theory for AI Safety",
      authors=["Joshua Fonseca Rivera", "Neil Shah", "David Demitri Africa", "Konstantinos Voudouris"], year=2026,
      summary="Behavioural-only IRT over 8 safety benchmarks incl. OR-Bench-Hard; names quantisation as a drift source to catch; no internals.",
      passages=[("provider routing, quantization, inference", "Audit application")]),
 dict(i=10, url="https://arxiv.org/pdf/2606.08044", title="When Behavioral Safety Evaluation Fails: A Representation-Level Perspective",
      authors=["Enyi Jiang", "Anders Gjølbye", "Yibo Jacky Zhang", "Sanmi Koyejo"], year=2026,
      summary="Over-refusal measured per model as a static-audit outcome; matched-random causal battery; quantisation robustness explicitly untested.",
      passages=[("whether it survives routine operations like quantization is untested", "Limitations"),
                ("a strong fixed probe on clean activations cannot tell it from the base", "Main result")]),
 dict(i=11, url="https://arxiv.org/pdf/2606.24952", title="Perfect Detection, Failed Control: The Geometry of Knowing vs. Steering in Language Models",
      authors=["Cosimo Galeone", "Anna Ettorre", "Minsu Park", "Giuseppe Ettorre", "Daniele Ligorio"], year=2026,
      summary="lm_head/logit-derived direction compared with activation directions (C3), causal steering (C5); prompt-site; not safety-refusal over-refusal.",
      passages=[("we collect residual-stream activations h at the last prompt token", "Method"),
                ("with 0 false refusals on the 50 real questions", "Intervention results")]),
 dict(i=12, url="https://arxiv.org/pdf/2607.01854", title="Has This Checkpoint Been Abliterated? A Two-Signal Audit and Its Failure Map",
      authors=["Gabriel Hurtado"], year=2026,
      summary="273-checkpoint registry with 37 benign fine-tunes/merges as hard negatives (FPR 0.11); reference-anchored; last-token; ablation left to future work.",
      passages=[("their z-sum separates 57 public abliterations from 37 benign", "Abstract"),
                ("which a last-token gap cannot see", "Limitations"),
                ("a layer-band ablation are left to future work", "Limitations")]),
 dict(i=13, url="https://arxiv.org/pdf/2606.29441", title="Closing the Activation-Cone Blind Spot: Response-Time Probing and Unified Defense",
      authors=["Subhadip Mitra"], year=2026,
      summary="Decode-site probe at first generated tokens, per input (C4 per-input).",
      passages=[("hidden state at the first few generated tokens", "Abstract/Intro")]),
 dict(i=14, url="https://raw.githubusercontent.com/JolanMc/Jorak/main/docs/METRICS.md", title="Jorak Model Scanner docs/METRICS.md (non-peer-reviewed tool)",
      authors=None, year=2026,
      summary="Community scanner: has a behavioural over-refusal veto on custom prompts; refusal-logit gap only proposed.",
      passages=[("behavioral_over_refusal", "Metrics list"),
                ("Écart de logit de refus", "Pistes (future)")]),
 dict(i=15, url="https://arxiv.org/pdf/2609.18471", title="First Token Matters: Understanding Safety Collapse in Large Reasoning Models",
      authors=["Yizheng Yang", "Haining Yu", "Yuechen Wang", "Yikai Hou", "Xing Fu", "Jinbo Yang", "Tianqing Zhu"], year=2026,
      summary="NEW (2026-09-16, CICAI 2026). Decode-site refusal-projection readout at generated tokens, Logit-Lens comparison, two-sided steering; XSTest used only as a behavioural outcome of defences; two R1-distilled checkpoints; no no-op controls.",
      passages=[("We project the hidden states of each generated token onto V", "Sec. 3 Refusal Projection Strength"),
                ("we measure over-refusal using the XSTest", "Sec. 4.2.1 Evaluation"),
                ("we use Logit Lens to trace the rank evolution of typical refusal tokens", "Sec. 3"),
                ("the refusal-related signal of LRMs drops sharply at the first generated token", "Abstract")]),
 dict(i=16, url="https://arxiv.org/pdf/2609.04721", title="Locating and Steering Refusal Beyond Attention",
      authors=["Preethi Carmel Bosco", "Gopalakrishnan Srinivasan"], year=2026,
      summary="NEW (2026-09-04). XSTest + OR-Bench-hard over-refusal of a gate; matched orthogonalised-random controls; write-site readout; no logit baseline, no no-op controls.",
      passages=[("Over-refusal is measured on XSTest", "Table 1"),
                ("far above an orthogonalized random control (Table 5), across", "Transfer results"),
                ("What is architecture-specific is not where the", "Intro")]),
 dict(i=17, url="https://arxiv.org/html/2606.15980", title="Do Activation Monitors Survive Model Updates? Benchmarking, Predicting, and Repairing Activation-Monitor Staleness",
      authors=["Evan Duan"], year=2026,
      summary="Nearest C1 neighbour: frozen per-input probes (incl. an XSTest-based refusal-compliance monitor) re-scored across 12 quantisation/LoRA/QLoRA update conditions on Gemma-2-2B-it and Qwen2.5-7B-Instruct. Probe AUC, not a per-checkpoint score's false alarm; updates not graded as behavioural no-ops.",
      passages=[("quantization-style updates largely preserve frozen probe performance, while fine-tuning-style updates frequently make probes stale", "Abstract"),
                ("refusal-compliance uses XSTest", "Experimental setup"),
                ("big-drop rates range from 57.1% for privacy/PII to 7.9% for refusal-compliance", "Findings"),
                ("LoRA-family updates produce 43.2–53.8% big-drop rates", "Findings")]),
 dict(i=18, url="https://arxiv.org/html/2606.10154", title="Quality Is Not a Safety Proxy Under Quantization",
      authors=["Sahil Kadadekar"], year=2026,
      summary="Quantisation can move behavioural refusal a lot; refusal-direction probes are weak/null separators of dangerous rows.",
      passages=[("entropy, refusal-direction, and calibration probes are weak or null separators of dangerous rows", "Abstract")]),
 dict(i=19, url="https://proceedings.neurips.cc/paper_files/paper/2024/file/f545448535dfde4f9786555403ab7c49-Paper-Conference.pdf",
      title="Refusal in Language Models Is Mediated by a Single Direction (NeurIPS 2024)", authors=None, year=2024,
      summary="System prompt changes behavioural ASR for Llama-2 but barely for Qwen.",
      passages=[("QWEN models maintain similar ASR regardless of system prompt inclusion", "Appendix, system prompt sensitivity"),
                ("22.6% vs 79.9% for LLAMA-2 7B", "Appendix, system prompt sensitivity")]),
 dict(i=20, url="https://arxiv.org/html/2406.12935v2", title="ChatBug: A Common Vulnerability of Aligned LLMs Induced by Chat Templates (AAAI 2025)",
      authors=["Fengqing Jiang","Zhangchen Xu","Luyao Niu","Bill Yuchen Lin","Radha Poovendran"], year=2024, summary="Chat-template format mismatches change behavioural safety.",
      passages=[("The format mismatch attack alters the default chat format", "Sec. ChatBug")]),
 dict(i=21, url="https://arxiv.org/html/2402.14499v2", title="\"My Answer is C\": First-Token Probabilities Do Not Match Text Answers in Instruction-Tuned Language Models",
      authors=None, year=2024, summary="First-token probability shifts under prompt constraints, but text-level refusal also shifts; not a fixed-behaviour precedent.",
      passages=[("This shows that the first token log probability gets shifted to the token", "Results")]),
 dict(i=22, url="https://arxiv.org/pdf/2406.05946", title="Safety Alignment Should Be Made More Than Just a Few Tokens Deep",
      authors=None, year=2024, summary="Alignment KL concentrated in first few tokens; motivates fragility of first-token metrics.",
      passages=[("the KL divergence is significantly higher in the first few tokens than for later tokens", "Sec. 2")]),
 dict(i=23, url="https://arxiv.org/html/2607.21063", title="QuantiBias: Benchmarking Quantization-Induced Bias in LLMs", authors=["Emilio Ferrara"], year=2026,
      summary="Quantisation leaves refusal evaluations unchanged while open-ended bias moves.",
      passages=[("quantization leaves the safeguards standard evaluations measure, refusal and multiple-choice bias avoidance, unchanged", "Abstract")]),
 dict(i=24, url="https://arxiv.org/html/2606.29581v1", title="The Joint Effect of Quantization and Sampling Temperature on LLM Safety Alignment: A Factorial Analysis",
      authors=["Hari Prasad","Ritam Pal"], year=2026, summary="AWQ INT4 largely preserves ASR for 7/9 models; one small model degrades sharply.",
      passages=[("with only SmolLM3-3B showing substantial degradation", "Abstract")]),
 dict(i=25, url="https://teendifferent.substack.com/p/apply_chat_template-is-the-safety", title="apply_chat_template() Is the Safety Switch (blog, not peer reviewed)",
      authors=None, year=None, summary="Anecdote: omitting the chat template flips small models from refusal to compliance.",
      passages=[]),
 dict(i=26, url="https://arxiv.org/abs/2603.27518", title="Over-Refusal and Representation Subspaces: A Mechanistic Analysis of Task-Conditioned Refusal in Aligned LLMs",
      authors=None, year=2026, summary="Over-refusal directions are task-dependent and distinct from the global harmful-refusal direction (per input, one model).",
      passages=[("whereas over-refusal directions are task-dependent", "Abstract")]),
 dict(i=27, url="https://arxiv.org/abs/2608.09624", title="Measuring the Wrong Thing: Internal Harmfulness Scores Anti-Rank Successful Jailbreaks",
      authors=None, year=2026, summary="Construct-validity warning: internal harm scores can move opposite to behaviour.",
      passages=[("so the attacks grow more dangerous while the prompts look safer to the score", "Abstract")]),
 dict(i=28, url="https://arxiv.org/abs/2604.09544", title="Large Language Models Generate Harmful Responses Using a Distinct Mechanism, Shared Across Harm Types",
      authors=["Hadas Orgad", "Boyi Wei", "Kaden Zheng", "Martin Wattenberg", "Peter Henderson", "Seraphina Goldfarb-Tarrant", "Yonatan Belinkov"], year=2026,
      summary="Orgad2026: verified id and 7 authors; owns the dissociation of harm generation from harm recognition.",
      passages=[("harmful response generation is dissociable from the ability to recognize and reason about harmfulness", "Abstract")]),
 dict(i=29, url="https://arxiv.org/abs/2507.03167", title="Where Do Reasoning Models Refuse? (ICML 2025 Workshop R2FM)",
      authors=["Kureha Yamaguchi", "Benjamin Etheridge", "Andy Arditi"], year=2025,
      summary="Yamaguchi2025: arXiv id 2507.03167 confirmed.", passages=[]),
 dict(i=30, url="https://raw.githubusercontent.com/elder-plinius/OBLITERATUS/cb4aec45/obliteratus/analysis/cross_layer.py",
      title="OBLITERATUS toolkit, obliteratus/analysis/cross_layer.py @ cb4aec45 (AGPL-3.0)", authors=None, year=2026,
      summary="CrossLayerAlignmentAnalyzer: pairwise cross-layer refusal-direction cosine matrix and cumulative angular drift; contains no '0.016' figure.",
      passages=[("class CrossLayerAlignmentAnalyzer:", "class definition"),
                ("the cumulative angular drift of the refusal direction through the network", "module docstring")]),
 dict(i=31, url="https://arxiv.org/pdf/2502.17420", title="The Geometry of Refusal in Large Language Models: Concept Cones and Representational Independence (ICML 2025)",
      authors=None, year=2025, summary="Wollschlager2025: multiple independent refusal directions / concept cones.",
      passages=[("multi-dimensional concept cones that mediate refusal", "Abstract")]),
 dict(i=32, url="https://arxiv.org/pdf/2604.18901", title="Harmful Intent as a Geometrically Recoverable Feature of LLM Residual Streams",
      authors=["Isaac Llorente-Saguer"], year=2026, summary="LlorenteSaguer2026a: harmful-intent detection survives abliteration (within 0.003 AUROC).",
      passages=[("match their instruction-tuned counterparts within", "Sec. 3.2")]),
 dict(i=33, url="https://arxiv.org/pdf/2603.27412", title="The Geometry of Harmful Intent: Training-Free Anomaly Detection via Angular Deviation (LatentBiopsy)",
      authors=["Isaac Llorente-Saguer"], year=2026, summary="LlorenteSaguer2026b: geometry survives refusal ablation (AUROC at most 0.015 below).",
      passages=[("geometry survives refusal ablation", "Abstract/Results")]),
 dict(i=34, url="https://huggingface.co/Qwen/Qwen3-4B-SafeRL", title="Qwen3-4B-SafeRL model card (Hugging Face)", authors=None, year=None,
      summary="Model card exists; cited as @misc.", passages=[]),
 dict(i=35, url="https://huggingface.co/Qwen/Qwen3-4B/raw/main/tokenizer_config.json", title="Qwen3-4B tokenizer_config.json", authors=None, year=None,
      summary="padding_side is not set (library default right padding) and pad_token is <|endoftext|>: relevant to AMS's batched last-position read.",
      passages=[("<|endoftext|>", "pad_token")]),
 dict(i=36, url="https://arxiv.org/html/2603.05773v2", title="Knowing without Acting: The Disentangled Geometry of Safety Mechanisms in Large Language Models",
      authors=None, year=2026, summary="Owns Recognition/Execution naming (inherited MUST-NOT-CLAIM).",
      passages=[("two distinct subspaces: a Recognition Axis", "Abstract")]),
]
