"""Quote-grade passages gathered in this pass (Blocks A, B, C, E).

Each entry: source key, URL the passage lives on, the regex used to find it, the verbatim
passage (a contiguous substring of the page text), and the claim it supports.
verify_passages.py re-fetches every URL and checks each passage is really on that page.
"""

PASSAGES = [
    # ---------------- Block A: the widened claim ----------------
    dict(key="NGLARE", url="https://aclanthology.org/2026.acl-long.1334.pdf", regex="safety-removed",
         passage="RL-aligned, base, and safety-removed ver",
         claim="N-GLARE's own Figure 1 example is the base / RL-aligned / safety-removed Qwen3-4B trio (the run's panel)."),
    dict(key="NGLARE", url="https://aclanthology.org/2026.acl-long.1334.pdf", regex="JSS metric exhibits",
         passage="demonstrate that the JSS metric exhibits high consistency with Red Teaming safety r",
         claim="N-GLARE's per-model JSS scalar tracks red-teaming safety rankings over 40+ models."),
    dict(key="NGLARE", url="https://aclanthology.org/2026.acl-long.1334.pdf", regex="hidden states of the last token across all layers",
         passage="we extract the hidden states of the last token across all layers at the decision-making cross-section",
         claim="N-GLARE reads the last token before the assistant response, at every layer: it is depth-resolved but prompt-site only."),
    dict(key="NGLARE", url="https://aclanthology.org/2026.acl-long.1334.pdf", regex="step-wise coupling",
         passage="JSS exhibits strong step-wise coupling with both UR and RR across layers",
         claim="N-GLARE prints layer-group Pearson/Spearman couplings of JSS with Unsafe Rate and Refusal Rate across DPO steps (Figure 7)."),
    dict(key="NGLARE", url="https://aclanthology.org/2026.acl-long.1334.pdf", regex="aggregate JSDs across all slices and layer groups",
         passage="aggregate JSDs across all slices and layer groups",
         claim="JSS is a model-level scalar aggregated over lower/middle/upper layer groups."),
    dict(key="NGLARE", url="https://aclanthology.org/2026.acl-long.1334.pdf", regex="refusal-style keyword matching",
         passage="This metric is based on refusal-style keyword matching.",
         claim="N-GLARE's Refusal Rate outcome is lexical keyword matching (undefined on a safe-completion model)."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="SafeVec",
         passage="Across Llama, Gemma, and Qwen families, RAS separates aligned models from uncensored and abliterated variants, correlates with output-level attack success rate, and is substantially faster than judge-based evaluation.",
         claim="RAS/SafeVec: a representation-level safety score over three families that separates aligned from uncensored/abliterated models and tracks ASR."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="reference model",
         passage="For each architecture family aa, we assume access to a safety-aligned reference model",
         claim="RAS is reference-anchored: it needs an aligned reference model per family."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="calibration models",
         passage="The reference model defines the refusal direction, while calibration models define how raw cosine similarities should be mapped into a comparable RAS scale.",
         claim="RAS also needs a family calibration set (aligned, uncensored, abliterated models)."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="last-token residual-stream",
         passage="We extract last-token residual-stream activations at each decoder layer.",
         claim="RAS reads only the last prompt token (prompt site)."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="For Qwen, we use layers",
         passage="For Llama, we use layers 22–30. For Gemma, we use layers 27–29. For Qwen, we use layers 22–26.",
         claim="RAS uses fixed, family-specific late layer windows; Qwen family = Qwen2.5-7B, not Qwen3."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="Model families",
         passage="We consider three open-weight model families: Llama-3.1-8B, Gemma-3-4B, and Qwen2.5-7B.",
         claim="RAS panel: three families, none of them Qwen3."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="calibrated within model families",
         passage="It is also calibrated within model families, so cross-family comparison depends on the quality of calibration models.",
         claim="RAS's own limitation: cross-family comparison depends on per-family calibration."),
    dict(key="RAS", url="https://arxiv.org/html/2606.25750", regex="216.88",
         passage="On average, RAS is 216.88",
         claim="RAS is about 217x faster than judge-based scoring."),
    dict(key="ALIGNED", url="https://aclanthology.org/2026.tacl-1.14.pdf", regex="less toxic models encode",
         passage="and find that less toxic models encode more infor-",
         claim="Aligned Probing (TACL 2026): across 20+ LMs, less toxic models encode more information about input toxicity."),
    dict(key="ALIGNED", url="https://aclanthology.org/2026.tacl-1.14.pdf", regex="correlate the average information",
         passage="we correlate the average information strength at each layer with the resulting output toxicity (EMT) across different LMs.",
         claim="Aligned Probing correlates a layer-resolved internal quantity with a graded behavioural rate (expected maximum toxicity) across models."),
    dict(key="ALIGNED", url="https://aclanthology.org/2026.tacl-1.14.pdf", regex="lower layers",
         passage="mation about the toxicity of text in lower layers.",
         claim="Aligned Probing locates the toxicity signal in lower layers."),
    dict(key="IRT", url="https://arxiv.org/abs/2608.05086", regex="ten adaptively",
         passage="roughly ten adaptively chosen items suffice for several individual benchmarks, cutting evaluation cost by 97-99%",
         claim="Behavioural IRT already owns the ~10-item regime."),
    dict(key="IRT", url="https://arxiv.org/abs/2608.05086", regex="192 language models",
         passage="We fit IRT models to eight safety benchmarks across 192 language models",
         claim="IRT is fit over 192 models."),
    dict(key="LVS", url="https://arxiv.org/html/2606.08044", regex="strong fixed probe",
         passage="a strong fixed probe on clean activations cannot tell it from the base",
         claim="Adverse prior: a dissociated model passes every static audit, including a fixed activation probe."),
    dict(key="LVS", url="https://arxiv.org/html/2606.08044", regex="2.5 to 3.1",
         passage="At the targeted mid layer the dissociated models score 2.5 to 3.1 times higher LVS than their bases.",
         claim="Only an intervention-based score (LVS) separates dissociated models from their bases."),
    dict(key="CYBER24", url="https://arxiv.org/html/2607.02714", regex="24 open-source",
         passage="large scale abliteration experiment on 24 open-source LLMs",
         claim="Abliteration susceptibility has been profiled over 24 open models."),
    dict(key="CYBER24", url="https://arxiv.org/html/2607.02714", regex="most reliable predictors",
         passage="identifying that the type of safety training and architecture are the most reliable predictors",
         claim="2607.02714 predicts abliteration susceptibility from model metadata, not from activations."),
    dict(key="OPSTATE", url="https://arxiv.org/html/2608.30748", regex="strongly predict jailbreak outcomes",
         passage="projections onto this axis strongly predict jailbreak outcomes",
         claim="Within one model, a refusal-axis projection predicts ASR across operational states (a per-condition, not per-checkpoint, analogue)."),
    dict(key="TRANSFER", url="https://arxiv.org/abs/2506.12913", regex="representational similarity under benign prompts",
         passage="representational similarity under benign prompts",
         claim="Cross-model representational similarity predicts jailbreak transfer (20 models, 33 attacks)."),

    # ---------------- Block B ----------------
    dict(key="CLS", url="https://arxiv.org/html/2606.22686v2", regex="Late Decision",
         passage="Models like Llama-3.1 process harmful and safe queries identically for 95% of their layers, diverging only at the final output head.",
         claim="B1: onset depth of harmful/safe divergence differs by family (Late Decision)."),
    dict(key="CLS", url="https://arxiv.org/html/2606.22686v2", regex="Early Divergence",
         passage="making them significantly more robust to linear steering.",
         claim="B1: early-divergence families (Qwen-2.5, ~40% depth) are described as more robust; qualitative link of onset depth to robustness."),
    dict(key="CLS", url="https://arxiv.org/html/2606.22686v2", regex="KL Divergence between hidden states",
         passage="We investigated where in the network the refusal decision occurs by measuring KL Divergence between hidden states of safe vs. harmful trajectories across network depth",
         claim="B1: the depth profile of harmful-vs-safe divergence is published across families."),
    dict(key="ZHOU24", url="https://arxiv.org/abs/2406.05644", regex="early layers",
         passage="can identify malicious and normal inputs in the early layers",
         claim="B1/B4 anchor (2024): malicious vs normal inputs are identified in early layers; alignment maps them to reject tokens later."),
    dict(key="ZHOU24", url="https://arxiv.org/abs/2406.05644", regex="reject tokens",
         passage="refines them to the specific reject tokens for safe generations",
         claim="B4 anchor: the refusal signal is refined into reject tokens across the middle-to-late layers (logit-lens-style buildup)."),
    dict(key="SAFELAYERS", url="https://arxiv.org/abs/2408.17003", regex="safety layers",
         passage="identifying a small set of contiguous layers in the middle of the model that are crucial for distinguishing malicious queries from normal ones",
         claim="B1 anchor: 'safety layers' are located at mid-depth."),
    dict(key="RBD", url="https://arxiv.org/html/2605.28553", regex="well before the final layer",
         passage="We find that refusal is linearly decodable well before the final layer",
         claim="B1: refusal is decodable at intermediate depth (per-input probes; used for attack search)."),
    dict(key="MITRA", url="https://arxiv.org/html/2606.29441", regex="structurally blind",
         passage="Our central finding is that prompt-time activation defenses are structurally blind to prefilling attacks",
         claim="B2: prompt-site vs response-site asymmetry is published (seven models)."),
    dict(key="MITRA", url="https://arxiv.org/html/2606.29441", regex="first few generated tokens",
         passage="a linear probe on the model’s hidden state at the first few generated tokens",
         claim="B2: the response-site probe is published as a per-input detector."),
    dict(key="FORESIGHT", url="https://arxiv.org/abs/2609.13737", regex="first-token hidden states",
         passage="relying solely on first-token hidden states",
         claim="B2: first-response-token hidden states forecast output harm (per input, two models)."),
    dict(key="HARC", url="https://arxiv.org/abs/2607.00572", regex="response-token positions",
         passage="Extending the analysis to response-token positions, we find that the model recognizes harmful content while it is generating that content, even when it failed to recognize the input as harmful at the prompt side.",
         claim="B2: HARC owns the response-site harmfulness readout."),
    dict(key="ROT", url="https://arxiv.org/html/2604.13386", regex="rotate gradually",
         passage="deception directions rotate gradually across layers rather than appearing at one location",
         claim="B3: direction rotation across depth is published (for deception, 12 models)."),
    dict(key="OBLIT", url="https://raw.githubusercontent.com/elder-plinius/OBLITERATUS/cb4aec45/obliteratus/analysis/cross_layer.py", regex="pairwise cosine",
         passage="computing pairwise cosine similarities between refusal directions across all layers",
         claim="B3: a public abliteration toolkit already computes the cross-layer refusal-direction cosine matrix."),
    dict(key="OBLIT", url="https://raw.githubusercontent.com/elder-plinius/OBLITERATUS/cb4aec45/obliteratus/analysis/cross_layer.py", regex="angular_drift",
         passage="angular_drift: list[float] # cumulative angular drift per layer",
         claim="B3/B4: the same toolkit outputs cumulative angular drift per layer."),
    dict(key="PERSONA", url="https://arxiv.org/html/2606.26161", regex="three stages",
         passage="This mediation unfolds across layers in three stages: input-side harmfulness detection, aggregation along the refusal direction, and late-layer expression (Lee et al., 2025).",
         claim="B4/B5: the detect -> aggregate -> express depth staging of refusal is published."),
    dict(key="PERSONA", url="https://arxiv.org/html/2606.26161", regex="downstream of where",
         passage="Refusal is therefore gated at the late-layer expression stage, downstream of where it is computed.",
         claim="B5: refusal is computed earlier than it is gated/expressed (a computed-to-expressed depth lag)."),
    dict(key="WRITE", url="https://arxiv.org/abs/2609.04721", regex="write site",
         passage="What is architecture-specific is not where the direction is steered but where it must be read.",
         claim="B5/B2: where refusal must be read differs from where it is steered (read/write site distinction)."),
    dict(key="HPD", url="https://arxiv.org/abs/2609.13534", regex="seven-dimensional",
         passage="This lightweight input moderator extracts a seven-dimensional feature record, slope, curvature, monotonicity, onset layer, and related statistics from the cross-layer projection sequence and classifies it with a 288-parameter MLP.",
         claim="B4/B9: depth-profile scalarisation (slope, onset layer) exists per prompt."),
    dict(key="GEOLITE", url="https://arxiv.org/abs/2605.20241", regex="margin profiles",
         passage="then summarizes the resulting margin profiles by boundary position, layer-to-layer change, and coarse shape. Across nine instruction-tuned backbones",
         claim="B4/B9: layer-wise margin-profile summaries over nine backbones, per prompt."),
    dict(key="ICS", url="https://arxiv.org/html/2608.16852", regex="ten labelled pairs",
         passage="a training-free activation readout calibrated from ten labelled pairs and scored by a single projection",
         claim="B9: a 10-pair diff-in-means activation readout is published (compliance domain)."),
    dict(key="ICS", url="https://arxiv.org/html/2608.16852", regex="bag-of-words",
         passage="a bag-of-words model matches its pooled generalisation exactly",
         claim="B9 adverse: the 10-pair readout does not beat a lexical baseline."),

    # ---------------- Block C: standing ledger, re-verified today ----------------
    dict(key="JORAK", url="https://raw.githubusercontent.com/JolanMc/Jorak/main/docs/METRICS.md", regex="reference-free",
         passage="on n'a pas besoin de générer ni de comparer à un original pour séparer *censuré* de *ablated*",
         claim="Jorak is parent-free (no original model needed)."),
    dict(key="JORAK", url="https://raw.githubusercontent.com/JolanMc/Jorak/main/docs/METRICS.md", regex="A = 0.705",
         passage="`A = 0.705`",
         claim="Jorak's worked value for an abliterated Qwen3-8B."),
    dict(key="LATBIOP", url="https://arxiv.org/html/2603.27412", regex="Geometry survives",
         passage="Geometry survives refusal ablation in both tested model families.",
         claim="Harm geometry survives abliteration (Qwen3.5-0.8B, Qwen2.5-0.5B)."),
    dict(key="HIGRF", url="https://arxiv.org/html/2604.18901", regex="abliterated",
         passage="three alignment variants (base, instruction-tuned, abliterated)",
         claim="2604.18901 covers base/instruct/abliterated across 12 models, 4 families."),
    dict(key="HIGRF", url="https://arxiv.org/html/2604.18901", regex="73°",
         passage="recover harm directions 73",
         claim="Two pooling choices recover harm directions 73 degrees apart."),
    dict(key="ORGAD", url="https://arxiv.org/html/2604.09544", regex="dissociable",
         passage="harmful response generation is dissociable from the ability to recognize and reason about harmfulness",
         claim="Orgad et al. own the generation/recognition dissociation."),
    dict(key="DSH", url="https://arxiv.org/html/2603.05773v2", regex="Recognition Axis",
         passage="two distinct subspaces: a Recognition Axis",
         claim="'Knowing without Acting' owns the Recognition/Execution naming."),
    dict(key="PDFC", url="https://arxiv.org/html/2606.24952", regex="0.1197",
         passage="it is identical before and after instruction tuning (0.1197 vs 0.1200)",
         claim="Weight-computable detection-vs-control cosine is flat across instruction tuning."),
    dict(key="PDFC", url="https://arxiv.org/html/2606.24952", regex="not a predictor",
         passage="not a predictor of how steerable a behavior is",
         claim="Adverse prior: the weight cosine is not a steerability predictor."),
    dict(key="AUDIT273", url="https://arxiv.org/abs/2607.01854", regex="attested reference",
         passage="it presumes an attested reference",
         claim="The 273-checkpoint audit is reference-anchored."),
    dict(key="AUDIT273", url="https://arxiv.org/abs/2607.01854", regex="AUROC 0.95",
         passage="separates 57 public abliterations from 37 benign fine-tunes, merges, and instruction-tunes at AUROC 0.95",
         claim="Audit numbers."),
    dict(key="BASU", url="https://arxiv.org/html/2603.18353", regex="98.2",
         passage="98.2% AUROC",
         claim="Basu probe AUROC."),
    dict(key="BASU", url="https://arxiv.org/html/2603.18353", regex="65 of 144",
         passage="detected 65 of 144 hazards overall (sensitivity 0.451",
         claim="Basu output sensitivity."),
    dict(key="BASU", url="https://arxiv.org/html/2603.18353", regex="zero corrections",
         passage="zero corrections and zero disruptions",
         claim="Zero-and-zero belongs to the SAE arm."),
    dict(key="BASU", url="https://arxiv.org/html/2603.18353", regex="19 of 79",
         passage="corrected 19 of 79 false negatives",
         claim="TSV arm corrected 19/79."),
    dict(key="KWON", url="https://arxiv.org/html/2607.14147v1", regex="0.24 vs 0.03",
         passage="the instruct model routes it to refusal tokens about 8",
         claim="Kwon logit-trace concentration."),
    dict(key="ANTIRANK", url="https://arxiv.org/html/2608.09624", regex="0.220",
         passage="outcome AUROC of 0.220",
         claim="Internal harmfulness scores anti-rank successful jailbreaks."),
    dict(key="HRCI", url="https://arxiv.org/html/2606.16349", regex="not itself a safety score",
         passage="so low coupling is not itself a safety score",
         claim="HRCI_repr authors: coupling is not a safety score."),
]

PASSAGES += [
    # ---------------- Block D: knowledge-action gap outside the clinical case ----------------
    dict(key="PYTHIA", url="https://arxiv.org/pdf/2609.01048v1", regex="43 of 48",
         passage="steering along that same reading direction remains null-equivalent in 43 of 48",
         claim="Block D: readable-but-not-steerable in 43 of 48 Pythia model x checkpoint cells (non-safety)."),
    dict(key="PYTHIA", url="https://arxiv.org/pdf/2609.01048v1", regex="caution against inferring steerability",
         passage="Our results caution against inferring steerability from probe accuracy",
         claim="Block D: the Pythia study's own conclusion."),
    dict(key="CAD", url="https://arxiv.org/html/2608.17843v1", regex="not always actionable",
         passage="Further analyses show that decodable information is not always actionable.",
         claim="Block D: decodable-but-not-actionable in a non-safety (CAD geometry) task, six models."),
    dict(key="SAEPROBE", url="https://arxiv.org/html/2609.18080v1", regex="Spearman",
         passage="the two rankings overlap only weakly (about 12",
         claim="Block D: probe-direction ranking vs behaviourally causal SAE features overlap ~12% (truth/deception, Gemma-2-9B)."),
    dict(key="ARITH", url="https://arxiv.org/html/2608.07528", regex="near-perfect accuracy",
         passage="Linear probes detect corrupted context in language models with near-perfect accuracy, yet this does not translate into reliable failure prediction.",
         claim="Block D: near-perfect probes do not predict failures (multi-hop arithmetic)."),
    dict(key="PDFC", url="https://arxiv.org/html/2606.24952", regex="AUC = 1.000",
         passage="perfect linear separability (AUC = 1.000 from layer 5)",
         claim="Block D in-safety: detection AUC 1.000 while the refusal-control direction sits ~83 degrees away."),
    # ---------------- B6 / B7 ----------------
    dict(key="ORSUB", url="https://arxiv.org/abs/2603.27518", regex="task-dependent",
         passage="whereas over-refusal directions are task-dependent",
         claim="B6: over-refusal directions are task-dependent and distinct from the global harmful-refusal direction (single model, per input)."),
    dict(key="ORSUB", url="https://arxiv.org/abs/2603.27518", regex="early transformer layers",
         passage="Linear probing suggests that the two refusal types are representationally distinct from the early transformer layers.",
         claim="B6: over-refusal vs harmful-refusal separable from early layers."),
    dict(key="MOREDIR", url="https://arxiv.org/abs/2602.02132", regex="one-dimensional control knob",
         passage="acting as a shared one-dimensional control knob",
         claim="B6: all refusal directions give nearly identical refusal/over-refusal trade-offs under steering."),
    dict(key="ALIGNED", url="https://aclanthology.org/2026.tacl-1.14.pdf", regex="encoding strength",
         passage="We then approximate the encoding strength (s) as the Pearson correlation between the predicted",
         claim="B7: Aligned Probing's internal quantity is a graded (continuous toxicity-level) encoding strength."),
    dict(key="THOUSAND", url="https://arxiv.org/pdf/2507.21141v1.pdf", regex="55 distinct harmfulness subconcepts",
         passage="55 distinct harmfulness subconcepts",
         claim="B7: harm is organised by category (55 sub-concepts), not ordinal severity."),
]

PASSAGES += [
    # ---------------- Block A: AMS (Google Cloud Activation-based Model Scanner) - the closer ----------------
    dict(key="AMS", url="https://arxiv.org/abs/2608.05578", regex="14 model configurations",
         passage="We validate AMS across 14 model configurations spanning 4 architecture families (Llama, Gemma, Qwen, Mistral) and four safety-modification categories (instruction-tuned, base, abliterated, uncensored fine-tunes).",
         claim="AMS scores 14 checkpoints over 4 families, abliterated and uncensored included."),
    dict(key="AMS", url="https://arxiv.org/abs/2608.05578", regex="Pearson r",
         passage="We measure behavioral compliance on 20 stratified JailbreakBench prompts per model and find that sigma on the harmful-content concept predicts compliance with Pearson r = -0.546 (p = 0.043), directionally but with meaningful noise.",
         claim="AMS predicts a graded behavioural rate (JailbreakBench compliance) across models from one model's activations: r = -0.546."),
    dict(key="AMS", url="https://arxiv.org/html/2608.05578", regex="Spearman correlation is weaker",
         passage="the rank-order Spearman correlation is weaker",
         claim="AMS's rank correlation is weaker (rho = -0.423, p = 0.13, not significant)."),
    dict(key="AMS", url="https://arxiv.org/abs/2608.05578", regex="71%",
         passage="Leave-one-out cross-validation of thresholds achieves 71% accuracy (10/14)",
         claim="AMS LOO threshold accuracy is 71%."),
    dict(key="AMS", url="https://arxiv.org/html/2608.05578", regex="16 contrastive pairs",
         passage="Run 16 contrastive pairs through model, extract activations at layers 40-80% depth",
         claim="AMS uses 16 contrastive pairs per concept at 40-80% depth: few prompts, depth-swept."),
    dict(key="AMS", url="https://arxiv.org/html/2608.05578", regex="16 pairs \\(32 prompts\\)",
         passage="Each concept uses 16 pairs (32 prompts).",
         claim="AMS prompt budget: 32 prompts per concept."),
    dict(key="AMS", url="https://arxiv.org/html/2608.05578", regex="final token position",
         passage="capture hidden states at the final token position",
         claim="AMS reads the final prompt token only (prompt site)."),
    dict(key="AMS", url="https://arxiv.org/html/2608.05578", regex="undetectable by activation-only probing",
         passage="This case is undetectable by activation-only probing of mid-residual-stream representations.",
         claim="AMS's own blind spot: behavioural fine-tunes that preserve mid-stream geometry (class iv)."),
    dict(key="AMS", url="https://arxiv.org/html/2608.05578", regex="refusal tokens at generation time",
         passage="token-level decoding analysis (measuring how the model treats refusal tokens at generation time)",
         claim="AMS names decode-time / response-site analysis as needed for its blind spot."),
    dict(key="AMS", url="https://arxiv.org/html/2608.05578", regex="principal open problem",
         passage="We treat this as the principal open problem motivated by the present work.",
         claim="AMS: the response-site/decode-time gap is its principal open problem."),
    dict(key="AMSREPO", url="https://raw.githubusercontent.com/GoogleCloudPlatform/activation-model-scanner/main/README.md", regex="No baseline required",
         passage="(No baseline required)",
         claim="AMS Tier 1 is reference-free."),
    dict(key="AMSREPO", url="https://raw.githubusercontent.com/GoogleCloudPlatform/activation-model-scanner/main/README.md", regex="collapsed safety directions",
         passage="show collapsed safety directions that AMS can detect in seconds",
         claim="AMS README: abliterated and uncensored models show collapsed safety directions."),
]
